version: "2"

linters:
  settings:
    errcheck:
      exclude-functions:
        - (io.Closer).Close
        - (*os.File).Close
        - (net/http.ResponseWriter).Write
        - fmt.Fprint
        - fmt.Fprintf
        - (*bufio.Writer).Flush
